server:
  port: 8083

service:
  version:
    ProviderService: 1.0.1

spring:
  application:
    name: dubbo-provider-service

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1   #随机端口
  registry:
    address: zookeeper://127.0.0.1:2181
  provider:
    timeout: 2000
